workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

deploy-pages:
  script:
    - cd client && npm run build
    - cp -r ./client/dist/ ./public/
  pages: true  # specifies that this is a Pages job
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
